database:
  type: SQLite # SQLite, MariaDB, MySQL, PostgreSQL
  host: localhost
  port: 3306
  name: database
  user: root
  pass: password
delayDayCycle: 300
disabledWorld:
  - "world_nether"
  - "world_the_end"